### PR TITLE
Feat(docs): Debugging with VSCode in Docker

### PR DESCRIPTION
**Pull request by Shelly011s**
I was thinking of mentioning "[NODEJS_SETUP.md](https://github.com/metabrainz/bookbrainz-site/blob/master/NODEJS_SETUP.md)" file since there are no instructions for running the server manually in docs.
Also, can I create a PR for committing changes in launch.son file required for this setup.

### CODE REVIEW

**Review by MonkeyDo — COMMENTED** [review]
That looks great @Shelly011s thanks a lot for opening this PR ! (and perfect timing too as the whole MetaBrainz team is having a documentation sprint :p )

Your additions look great, nothing to add for the content.

I would however suggest that we rearrange the existing text and your new text to make it clearer that there are two use cases: running the code directly in VSCode and running the code in Docker.
I'm thinking that distinction won't be clear to someone who is new to all this…

We can have two sub-sub-sections, one for each use case: "Running the code with Docker" first, as this what we usually recommended, and "Running the code with VSCode" after that.

As you mentioned, in that second sub-section we would want to mention manual installation of the dependencies. But rather than point to the bookbrainz-site repo, could I ask for another favor?
Could you please (in another PR) move any of the documentation files that you find in the root of the bookbrainz-site repo to this documentation repo? That's really where they should live !

Thanks a lot in advance for your help !

**Comment by MonkeyDo** [comment]
Oh, and I forgot to say, yes please do open a PR in bookbrainz-site to add your improvements to the vscode launch.json file !

**Comment by Shelly011s** [comment]
There are 3 files that needs to be moved in this repo namely [DEPENDENCIES_MANUAL_INSTALL.md](https://github.com/metabrainz/bookbrainz-site/blob/master/DEPENDENCIES_MANUAL_INSTALL.md), [INSTALLATION_TROUBLESHOOTING.md](https://github.com/metabrainz/bookbrainz-site/blob/master/INSTALLATION_TROUBLESHOOTING.md), [NODEJS_SETUP.md](https://github.com/metabrainz/bookbrainz-site/blob/master/NODEJS_SETUP.md).
But going through the [BookBrainz Developer Docs](https://bookbrainz-dev-docs.readthedocs.io/en/latest/index.html) I noticed there are no guides for manual installation or set up which is addressed by "DEPENDENCIES_MANUAL_INSTALL.md" as well as no guide for debugging in vscode when the set up is done manually. 
So I suggest that there should be a section for manual set up in which there will be either a redirection to "DEPENDENCIES_MANUAL_INSTALL.md" or the entire content is copied there. Same should be done for  "Running the code with VSCode" using "NODEJS_SETUP.md" .

**Comment by MonkeyDo** [comment]
Yes, that sounds exactly right.
I think we should aim to move the documents from bookbrainz-site to this repo (bookbrainz-dev-docs), then remove the old ones in bookbrainz-site so we don't have duplicates.

One of the files does already exist in the docs: INSTALLATION_TROUBLESHOOTING.md  is more or less here: https://bookbrainz-dev-docs.readthedocs.io/en/latest/docs/troubleshooting.html
There is a Postgres section that is missing, which should be moved over, but the rest seems to be the same file.

**Comment by Shelly011s** [comment]
I have made the desired changes. Once this PR is approved, I will remove the said duplicates from bookbrainz-site repo to prevent redundancy. Let me know if something needs to be improved.

**Review by MonkeyDo — APPROVED** [review]
Thank you ! :rocket:

**Pull request merged**
